### ISSUE TITLE
Unable to post project

### ISSUE THREAD

**Issue by mvidberg** [koad/gencapp.com#14]
I am getting the "Region is required" error when attempting to submit a project.
![region-error](https://cloud.githubusercontent.com/assets/871411/17340353/c2407fde-58bd-11e6-97cc-b4cd0bf093c2.jpg)

**Comment by mvidberg** [comment]
As we discussed in the meeting, project add page needs same code that was added to business add page.

**Comment by ve-koad** [comment]
Fixed

**Comment by mvidberg** [comment]
![regionstill](https://cloud.githubusercontent.com/assets/871411/18054802/53a61efa-6dd3-11e6-8f7c-47fd676a3c77.jpg)
I am still getting the "Region is required" error on both main site and test site on Firefox.  So unless you forgot to push changes, this is not actually fixed.
